### ISSUE TITLE
FrostyFix not working at all

### ISSUE THREAD

**Issue by wyldcrd** [Dyvinia/FrostyFix#20]
When I enable mods globally and boot it up through epic, origin starts but then doesn't start battlefront2. When I use launch games with mods enabled through origin or epic it starts but I get no mods. Every now and then when I start frosty fix I get this crash message:

**Comment by wyldcrd** [comment]
The invocation of the constructor on type 'FrostyFix4.MainWindow' that matches the specified binding constraints threw an exception.

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix4.MainWindow.CheckStatus()
   at FrostyFix4.MainWindow..ctor()

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SaiyanDaiko** [comment]
Yea I've been getting this too and today was my first day just trying to play Battlefront 2 with mods and I have had no success

**Comment by wyldcrd** [comment]
still nothing after a week and a half of self troubleshooting and being unable to find the problem
sadge

**Comment by CameronBawn10** [comment]
I hope this gets fixed ASAP im nearly finished doing my mods

**Comment by Dyvinia** [comment]
start as admin

**Comment by CameronBawn10** [comment]
wdym start as admin

**Comment by Dyvinia** [comment]
![image](https://user-images.githubusercontent.com/13797470/173164826-fee534b2-23e7-4931-a5be-31773961e8d0.png)

**Comment by CameronBawn10** [comment]
i have done this already

**Comment by wyldcrd** [comment]
same, fixes the problem but the game still doesnt start/have mods.

**Comment by wyldcrd** [comment]
![image](https://user-images.githubusercontent.com/106457611/173168544-2d65db70-037c-462b-87d0-a6b55e955ab1.png)
I doubt my mods have anything to do with this issue but maybe

**Comment by wyldcrd** [comment]
I have tried all sorts of combinations of mods and still nothing.

**Comment by CameronBawn10** [comment]
ive got my mods but the game is rly slow

**Comment by wyldcrd** [comment]
@CameronBawn10 turn down the graphics

**Comment by wyldcrd** [comment]
Dyvinia could my game being in E:\EDrive\STAR WARS Battlefront II be the problem?

**Comment by wyldcrd** [comment]
Dyvinia I ran FrostyFix as admin and got:

`Exception has been thrown by the target of an invocation.

System.NullReferenceException: Object reference not set to an instance of an object.
   at FrostyFix4.MainWindow.CheckStatus()
   at FrostyFix4.MainWindow..ctor()

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstance(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by wyldcrd** [comment]
I'm done with this and everything I have tried won't work, clean install of bf2 origin epic frosty and frostyfix so I am closing this issue.

**Comment by Dyvinia** [comment]
Can you try this and see if it gives a more detailed error (You will need .NET6 Runtime installed)

[FF5.zip](https://github.com/Dyvinia/FrostyFix/files/8951626/FF5.zip)

**Comment by wyldcrd** [comment]
I will try it when i’m able to (most likely this Saturday)

**Comment by Dyvinia** [comment]
Should now be fixed in 4.5.1

**Comment by wyldcrd** [comment]
It fixed everything @Dyvinia ! Thanks a ton!

**Comment by wyldcrd** [comment]
Cannot process request because the process (16456) has exited.

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix4.MainWindow.CheckStatus()
   at FrostyFix4.MainWindow.<DisableMods>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
