### ISSUE TITLE
crashing 

### ISSUE THREAD

**Issue by flythh** [Dyvinia/FrostyFix#23]
as soon as i open it it just instant crashes

**Comment by Dyvinia** [comment]
please send more info than 'it just instant crashes'

**Comment by flythh** [comment]
> 

as soon as i open frosty fix it just closes instantly it

**Comment by flythh** [comment]
Nvm i got it to work but i open it up and this is the error i get The invocation of the constructor on type 'FrostyFix5.MainWindow' that matches the specified binding constraints threw an exception.

System.Collections.Generic.KeyNotFoundException: The given key 'GAME_DATA_DIR' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.Specialized.StringDictionaryWrapper.get_Item(String key)
   at FrostyFix5.MainWindow.CheckStatus() in C:\Users\Dulana\source\repos\FrostyFix5\Windows\MainWindow.xaml.cs:line 161
   at FrostyFix5.MainWindow..ctor() in C:\Users\Dulana\source\repos\FrostyFix5\Windows\MainWindow.xaml.cs:line 53
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wyldcrd** [comment]
Run as administrator and check version

**Comment by wyldcrd** [comment]
Use newest version
