### ISSUE TITLE
(Cannot process request because the process (4840) has exited.)

### ISSUE THREAD

**Issue by wyldcrd** [Dyvinia/FrostyFix#24]
Cannot process request because the process (4840) has exited.

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix4.MainWindow.CheckStatus()
   at FrostyFix4.MainWindow.<LaunchWithMods>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The game starts normally when I disable mods, select epic games, and start it. Well, now we are here @Dyvinia .

**Comment by wyldcrd** [comment]
Tried Origin and EA store and I get the same error

**Comment by wyldcrd** [comment]
And Global just doesn't allow me to start it.

**Comment by wyldcrd** [comment]
No incompatibilities in my mods and it is a fresh install of BF2

**Comment by Dyvinia** [comment]
Can you try this and see what error it gives if an
[FF5-test-6-28.zip](https://github.com/Dyvinia/FrostyFix/files/9005905/FF5-test-6-28.zip)
y

**Comment by wyldcrd** [comment]
Cannot process request because the process (25768) has exited.

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix.MainWindow.CheckStatus() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 139
   at FrostyFix.MainWindow.DisableMods() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 330
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wyldcrd** [comment]
i got that by clicking start twice on frostyfix

**Comment by wyldcrd** [comment]
ima try global

**Comment by Dyvinia** [comment]
try running as admin

**Comment by wyldcrd** [comment]
clicked start twice and got a different number
Cannot process request because the process (9176) has exited.

   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix.MainWindow.CheckStatus() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 132
   at FrostyFix.MainWindow.DisableMods() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 330
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dyvinia** [comment]
try this one
[FF5-test2-6-28.zip](https://github.com/Dyvinia/FrostyFix/files/9005953/FF5-test2-6-28.zip)

**Comment by wyldcrd** [comment]
The invocation of the constructor on type 'FrostyFix.MainWindow' that matches the specified binding constraints threw an exception.

System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix.MainWindow.CheckStatus() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 133
   at FrostyFix.MainWindow..ctor() in C:\Users\Dulana\source\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 50
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dyvinia** [comment]
now running as admin should work

**Comment by wyldcrd** [comment]
forgot that part

**Comment by wyldcrd** [comment]
ran as admin tried origin epic EA and global, didnt start game.

**Comment by wyldcrd** [comment]
said connecting to origin then origin closed

**Comment by Dyvinia** [comment]
FrostyFix doesn't start the game for you, you do that yourself

**Comment by wyldcrd** [comment]
no i did start it for myself

**Comment by wyldcrd** [comment]
i clicked on the tile

**Comment by wyldcrd** [comment]
![image](https://user-images.githubusercontent.com/106457611/176319602-4c6cb06c-be4c-426b-aa3c-3b863c18ed50.png)

**Comment by wyldcrd** [comment]
It opens epic, i click the tile, opens origin and says: Connecting to origin, Origin closes and bf2 doesnt start

**Comment by Dyvinia** [comment]
do you have origin pre-installed or are you using the origin that comes with epic games

**Comment by wyldcrd** [comment]
pre installed because i own fallen order on steam

**Comment by wyldcrd** [comment]
and im guessing epic opens both and screws something up?

**Comment by Dyvinia** [comment]
If you have origin preinstalled, you use the origin option in frostyfix

**Comment by Dyvinia** [comment]
since the crash is resolved, im going to close the issue. for further support go to the BattlefrontModding discord server

**Comment by wyldcrd** [comment]
that server requires a phone number to verify and i dont have one
