### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by angelfi890** [Dyvinia/FrostyFix#31]
Arithmetic operation resulted in an overflow.

   at System.IntPtr.ToInt32()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment._GetPeb32(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment._GetPEnv(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment._GetEnvStream(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.ProcessEnvironment.ReadVariables(IntPtr hProcess)
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix.MainWindow.CheckStatus()
   at FrostyFix.MainWindow..ctor() in D:\Development\Visual Studio\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 46
   at FrostyFix.App.OnStartup(StartupEventArgs e) in D:\Development\Visual Studio\repos\FrostyFix\App.xaml.cs:line 39
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wyldcrd** [comment]
Have you tried running as administrator? @angelfi890

**Comment by Dyvinia** [comment]
run as administrator
