### ISSUE TITLE
To run this application you must install missing frameworks (NEW)

### ISSUE THREAD

**Issue by ChefP00H** [Dyvinia/FrostyFix#38]
I already downloaded both new core and frameworks (6.07 for Core AND 4.8 for Frameworks), but when I try to open frostyfix, it always says that I need to download missing frameworks. When I use the older versions, it opens but doesn't work.

**Comment by ChefP00H** [comment]
Also, now the older versions don't work and say this when I try opening them: The invocation of the constructor on type 'FrostyFix4.MainWindow' that matches the specified binding constraints threw an exception.

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at Gapotchenko.FX.Diagnostics.Pal.Windows.PalAdapter.ReadProcessEnvironmentVariables(Process process)
   at Gapotchenko.FX.Diagnostics.ProcessExtensions.ReadEnvironmentVariables(Process process)
   at FrostyFix4.MainWindow.CheckStatus()
   at FrostyFix4.MainWindow..ctor()

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by creeperman17** [comment]
same

**Comment by ChefP00H** [comment]
I fixed it by downloading frosty fix version 4.2.1 and then it worked. IF it doesn't open, run it as administrator (you'll have to do that every time but it's literally just the click of a button). Also to run it as Administrator, click the windows search bar, go on frosty fix, and it should give you the option of running it as administrator.

**Comment by Dyvinia** [comment]
You need .NET **Desktop** Runtime 6.0.7, you likely didn't download the right version (
