### ISSUE TITLE
FrostyFix Crashes Steam, Crashes Self

### ISSUE THREAD

**Issue by kaosTwo** [Dyvinia/FrostyFix#54]
I have jumped through hoops to get even vanilla Dragon Age: Inquisition running on Steam at all today, and managed that. Loaded it sucessfully through FrostyMM, though with the already long known issue that is the absence of my modlist.
Every time I try to launch using Frosty Fix, Steam exits entirely, meaning I have to re-open and re-login every time, and Frosty Fix itself crashes and gives me the attatched crashdump (in italic). I have tried this alongside DatapathFix (I'm having tech issues with that too but I'll log an official issue for that for your organisation), to no avail. Swear EA is trying to screw us all over covertly.
Thanks for readin'.

_An error occurred trying to start process 'E:\Gaming\DA-I Mods\Frosty\FrostyModManager.exe' with working directory 'E:\Gaming\DA-I Mods\Frosty'. The system cannot find the file specified._

   _at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FrostyFix.MainWindow.LaunchGame() in D:\Development\repos\FrostyFix\Windows\MainWindow.xaml.cs:line 292
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)_

**Comment by Dyvinia** [comment]
Use DatapathFix
